[project]
name = "t2-eda"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "notebook>=7.3.3",
    "pandas>=2.2.3",
    "requests>=2.32.3",
]
